###Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"password"
}

### logout
DELETE    http://localhost:5000/auth/logout


### get Me
GET  http://localhost:5000/auth/me


### get token
GET http://localhost:5000/token/eae1469a-a615-401d-961b-5dda7b73236c

###register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name":"test6",
    "email":"test6@gmail.com",
    "password":"password"
}

### first token
GET http://localhost:5000/auth/first_token/c0b2d38b-69e2-469e-9772-23a491bfc20a