### Login 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"test2@gmail.com",
    "password":"password"
}
###

### add chats
POST  http://localhost:5000/chats
Content-Type: application/json

{
    "member":["35cf9e66-111f-4ace-b8dd-6993aa13aaea"],
    "group_name":"Test"
}

### add chats
POST  http://localhost:5000/chats
Content-Type: application/json

{
    "contact_id":"35cf9e66-111f-4ace-b8dd-6993aa13aaea"
}

### get chats
GET http://localhost:5000/chats?name=

### get contacts
GET http://localhost:5000/contacts

### get chat
GET http://localhost:5000/chats/1ed388c4-f6bc-4420-a03f-ef067060a658

### delete chats
DELETE http://localhost:5000/chats/e63424a5-0c4a-459d-b408-081f94dba9f8