#### get all
GET http://localhost:5000/users

### Login 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"super@gmail.com",
    "password":"password"
}

### logout
DELETE    http://localhost:5000/auth/logout

### Login 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"password"
}


### add contact
POST  http://localhost:5000/contacts
Content-Type: application/json

{
    "userId":"1fbde93d-86a2-4c4a-bd75-f3a37b7514d2"
}

### get contacts
GET http://localhost:5000/contacts?name=

### get contact berdasarkan contact_id
GET http://localhost:5000/contacts/7d3ebb98-3c90-473f-a5d0-9c2ad7b6a7fc

### delete contact
DELETE http://localhost:5000/contacts/425aea17-8035-4855-8fbe-fbfa31d06017