### message (menggunakan chat id)
POST http://localhost:5000/messages/1ed388c4-f6bc-4420-a03f-ef067060a658
Content-Type: application/json

{
    "message":"coba"
}


# menggunkan contoct id
### get messages 
GET http://localhost:5000/messages/7b49450e-d71d-4b91-ab16-68e9660f23c1